### PR TITLE
Node integration

### PR DESCRIPTION
**Pull request by ozgunozerk**
Kind of a big PR. 

Introduces node integration to subspace desktop. Turning it into a standalone app.

Also solves #79, #48 and #61.

Question: should we bump the version into 0.2.0 with this PR (I can do a quick rebase), or should that be another PR? 
I don't know if there is a best practice for that.

### CODE REVIEW

**Review by nazar-pc — APPROVED** [review]
Looks fine to me, I'm just wondering maybe we should change bootstrap node to point to the (currently) inactive farmnet, such that it works even before we make a switch.

**Comment by ozgunozerk** [comment]
We actually discussed that in the meeting. We will be making the switch pretty soon, that's why we decided to make this change and be ready for it. But I'm fine with both strategies :)
I believe @1devNdogs and @ImmaZoni are more knowledgeable on this issue than me

**Comment by nazar-pc** [comment]
Well, it will be broken before the switch though, meaning we can't test the final builds. It also means that when we do the switch next time, we'll break the previously produced builds instead of giving them some more time to switch. I think setting more specific endpoint is actually beneficial because of that.

**Comment by 1devNdogs** [comment]
> Well, it will be broken before the switch though, meaning we can't test the final builds. 

Oh, I hadn't considered that. I have updated values to target the inactive network on `aries-farm-rpc-b`

**Review by nazar-pc — DISMISSED** [review]

**Comment by nazar-pc** [comment]
It would be nice to add advanced settings in the future where we can customize bootstrap nodes and other settings.

**Review by 1devNdogs — DISMISSED** [review]

**Comment by ozgunozerk** [comment]
So I guess we will wait for the switch to happen, then update the version and bootnodes in the code, and have a release. 
In the meantime, we can merge this PR. 
I have squashed the last tweak commit, and enabled auto-merge.

**Review by nazar-pc — APPROVED** [review]
We don't need to update bootnodes after, they'll continue to work and for next release of node we'll need new desktop release anyway.

**Pull request merged**
