### PR TITLE
Upgrade Tauri to latest version

### PR DESCRIPTION
**Pull request by nazar-pc**
I considered downgrading `zstd` version in a fork, but the simpler solution for now is to just disable compression.

Compression wasn't there before in Tauri (at least there was no such feature) and Debian package size got much smaller after upgrade anyway (30.2M -> 22.7M).

### CODE REVIEW

**Comment by nazar-pc** [comment]
Please test if this actually works, I only checked that it compiles on Linux.

**Review by ozgunozerk — CHANGES_REQUESTED** [review]
Unfortunately on macos, it creates the runtime error on quasar side:
`Scoped command osascript not found`. 
And produces an app with a blank screen with no functionality.
image

I will inspect this further, but this is not ready to merge yet.

**Comment by nazar-pc** [comment]
For quasar we might need Leo's help

**Comment by 1devNdogs** [comment]
We need to update a few **settings** and **security checks** on **tauri.conf.json**. I have found at least these two as critical.

## TO FIX `fs scope` 

Solution:
- The `scope` error is related to [this](https://tauri.studio/docs/api/js/modules/fs#security) new configurations. Adding `scope` will be able to read and write files and dirs on it. On **Linux** at least I was getting similar errors and were solved by adding this  to **tauri > allowlist > fs > scope** config.

Two problems:
- The user will be **limited to this scope**, this will be a **problem** with selecting `non-HOME plot directory`, like another partition, external drives, etc. 
- Also, this configuration will be applied on the build and looks we can not update the scope after, still checking if there is another way to set this or maybe update the scope on user selection. I still can't find a solution to this.

@ozgunozerk  can you try adding this on tauri.conf.json 

`      
    "fs": {
        "all": true,
        "scope": ["$HOME/*"]
      }
`

## TO FIX `Shell scope:`

Looks we need to apply some confs also, but I can not test in here. @ozgunozerk this will probably solve the `applescript` execution problems. Just need to find the correct configuration.

https://tauri.studio/docs/api/js/modules/shell and https://tauri.studio/docs/api/js/modules/shell#security

**Comment by 1devNdogs** [comment]
Also check #90, will be fixed automatically if we get this upgrade running.

**Comment by ozgunozerk** [comment]
tauri action v0.3 creates problem. I believe it is not yet stable (also it is not `latest` in the release section of their repo). Switching back to v0.2 for now.

**Comment by ozgunozerk** [comment]
with march 03-23 update on rust nightly, `ring` create is creating problems on the building phase.
<details>
error: no rules expected the token `aarch64_apple`
   --> /Users/ozgunozerk/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/src/cpu.rs:257:13
    |
165 |     macro_rules! features {
    |     --------------------- when calling this macro
...
257 |             aarch64_apple: true,
    |             ^^^^^^^^^^^^^ no rules expected this token in macro call

error[E0425]: cannot find value `AES` in module `cpu::arm`
   --> /Users/ozgunozerk/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/src/aead/aes.rs:381:65
    |
381 |         if cpu::intel::AES.available(cpu_features) || cpu::arm::AES.available(cpu_features) {
    |                                                                 ^^^ not found in `cpu::arm`
    |
help: consider importing this constant
    |
15  | use crate::cpu::intel::AES;
    |

error[E0425]: cannot find value `PMULL` in module `cpu::arm`
   --> /Users/ozgunozerk/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/src/aead/gcm.rs:315:26
    |
315 |             || cpu::arm::PMULL.available(cpu_features)
    |                          ^^^^^ not found in `cpu::arm`

error[E0425]: cannot find value `ARMCAP_STATIC` in this scope
   --> /Users/ozgunozerk/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/src/cpu.rs:235:41
    |
235 |             if self.mask == self.mask & ARMCAP_STATIC {
    |                                         ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `ARMCAP_STATIC` in this scope
   --> /Users/ozgunozerk/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/src/cpu.rs:288:36
    |
288 |     static mut GFp_armcap_P: u32 = ARMCAP_STATIC;
    |                                    ^^^^^^^^^^^^^ not found in this scope
</details>

**Comment by nazar-pc** [comment]
Here is a report in:
* ring: https://github.com/briansmith/ring/issues/1469
* rust: https://github.com/rust-lang/rust/issues/95267

**Comment by ozgunozerk** [comment]
Thanks Nazar, I've opened a issue about `ring`, I will keep an eye on these threads you provided and update to `nightly` when this issue is resolved. For now, I believe it is ok to continue with 2022-02-15 version of rust.

**Comment by ozgunozerk** [comment]
Tested on macos and windows, it is working

**Review by ozgunozerk — APPROVED** [review]

**Pull request merged**
