### PR TITLE
make farmer and nodesync concurrent

### LINKED ISSUE #72: start the farmer without waiting for sync
Now that the protocol supports plotting whilst syncing, we should start the farmer in the frontend in parallel with syncing the node.

### PR DESCRIPTION
**Pull request by ozgunozerk**
Keep in mind that I'm not experienced in JS, and the changes in this PR may not be following the best practices. 

This PR aims to fix #72

 After you guys approve/improve what I've done here, I will remove the commented out parts.

### CODE REVIEW

**Comment by ozgunozerk** [comment]
Tested on macos, it is working (plotting done, syncing done, producing blocks, everything works)

**Review by 1devNdogs — APPROVED** [review]

**Comment by 1devNdogs** [comment]
Looks fine, i moved few things to actually show this concurrent sync status.

- Diplay **node** sync status and progress %
- Display **farmer** plotting status and progress %
- Moved timers to own function.

Next button is enabled after both, node and farmer are fully synced. **As always**

This is how it looks:
image

**Review by 1devNdogs — DISMISSED** [review]

**Review by nazar-pc — APPROVED** [review]
@1devNdogs Unless changes are required for this PR, let's not push things on top, but rather as a separate PR. PRs are free to create.

**Comment by 1devNdogs** [comment]
@nazar-pc Thanks for the review. And sure, will use a separate PR next time, after pushing on top I realized the problems with tracking changes and reviews.

**Pull request merged**
